### ISSUE TITLE
Only first log sent/received

### ISSUE THREAD

**Issue by matthiasfru** [logdna/python#3] opened 2017-02-22 18:05 UTC
Hi, 
when trying to send logging info only the first message after setting up the logger is sent and shown in the web interface, the others are not sent/received but there is no python Error. This problem is reproducible using the exact simple code on the Readme page. I’m using python 3.5 and logdna 1.0.2.
Thanks!

**Comment by respectus** [comment] 2017-02-22 19:44
Hi @matthiasfru , thanks for keeping up with the module. Unfortunately, I am unable to reproduce the issue using python 3.5.0 and logdna 1.0.2. There is also a test script in this repo, could you try running that with python 3.5.0 and let me know if the issue persists? I can help debug this further if you would like to send me your admin email through intercom, thanks!

**Comment by matthiasfru** [comment] 2017-02-24 14:21
The issue did persist using the test script, however the problem was fixed when using a virtualenv (works for me). Maybe there was some conflict with other packages...

**Comment by respectus** [comment] 2017-02-24 18:53
Thanks for raising this issue @matthiasfru , it will be valuable to others who may face the same errors. I'm glad virtualenv worked for you, I use pyenv for Python version management and it works well for me. I'll close this issue, since it is working for you now. Please do let me know through intercom if you have any other questions or concerns, thanks!

**Closed by respectus** 2017-02-24 18:53 UTC

**Comment by guillaumemarc** [comment] 2017-04-11 16:31
this issue is not solve it is du to :
   if not self.flusher:
                self.flusher = Timer(defaults['FLUSH_INTERVAL'], self.flush())

you not start self.flush() in a thread but directly 
the correct code will :
   if not self.flusher:
                self.flusher = Timer(defaults['FLUSH_INTERVAL'], self.flush)
                self.flusher.start()
