### ISSUE TITLE
Django unable to start

### ISSUE THREAD

**Issue by PavelPancocha** [logdna/python#103] opened 2023-07-23 20:41 UTC
From version 1.18.8 I am not able to start up the django project with `logdna`

I think some blocking thread from these [changes](https://github.com/logdna/python/commit/033a63f7043e2e48889be23a7e90446ba47cb71b) could be the reason for it.

1.18.7 works fine.

**Comment by shawkinsmezmo** [comment] 2023-07-24 21:12
Hi @PavelPancocha. I'm investigating the django startup issue. The changes in question were implemented in order to address an issue with version 1.18.7 where the python logger would silently drop logs due to improper locking semantics around shared state. Would you be able to share an example of your logging config from the django project in question? This will help me to more quickly reproduce the issue in question. Thanks!

**Comment by shawkinsmezmo** [comment] 2023-07-25 06:51
Hi @PavelPancocha We have a fix en route that should hopefully address this issue. I apologize for the inconvenience and appreciate your patience as we work through this.

**Comment by PavelPancocha** [comment] 2023-07-25 08:24
Thank you @shawkinsmezmo - if needable, I can try to prepare some "minimum example app" that would show the issue. From what I tested so far the config doesn't play a role here. Thank you!

**Comment by dbartenstein** [comment] 2023-07-26 09:52
@shawkinsmezmo do you already have an ETA for the fix? Thanks a lot! :bow:

**Comment by shawkinsmezmo** [comment] 2023-07-26 16:28
Hi @dbartenstein. @PavelPancocha - Can you give the latest package a try and let me know if it resolves your issues? Thanks!

**Comment by PavelPancocha** [comment] 2023-07-26 17:06
@shawkinsmezmo Unfortunatelly, doesnt seems to work. Our docker build hangs on `python3 manage.py collectstatic`

**Comment by shawkinsmezmo** [comment] 2023-07-26 17:08
@PavelPancocha Interesting. I tested the latest release specifically with Django. Can you confirm the version that you tested with?

**Comment by PavelPancocha** [comment] 2023-07-26 17:26
`django==3.2.20`

If you will not be able to get it, I should have tomorrow some time to try to compile some "minimum example"

**Comment by shawkinsmezmo** [comment] 2023-07-26 17:41
@PavelPancocha I meant can you confirm the version of the LogDNA python logging client that you tested with? It should be version `1.18.11`

**Comment by PavelPancocha** [comment] 2023-07-26 18:36
Hi,

I updated my Docker file with this:

```
RUN pip show django
RUN pip show logdna
RUN timeout 20 python3 manage.py check || true
RUN python3 -m trace --trace manage.py check
```
Fails on check

What I get (very long): https://drive.google.com/file/d/1M50gLE9h0OQzoRcbgQ2Ljjkjm6p6M20P/view?usp=sharing

As you can see, it got clipped, but it could lead you somewhere

**Comment by PavelPancocha** [comment] 2023-07-26 18:48
I see the part with pip show was cut, but yes, it is Django 3.2.20 & logdna 1.18.11

**Comment by shawkinsmezmo** [comment] 2023-07-27 22:51
@PavelPancocha @dbartenstein  Can you give version `1.18.12` a try? I traced the root cause of the issue to the logdna handler overwriting a variable of the base `logging.Handler` class, which should be addressed with the latest release.

**Comment by PavelPancocha** [comment] 2023-07-28 12:26
@shawkinsmezmo seems to solve the problem! Thanks 🙇🏻‍♂️

**Comment by shawkinsmezmo** [comment] 2023-08-01 20:38
Closing this issue as resolved. Thanks for everyone's help on this.

**Closed by shawkinsmezmo** 2023-08-01 20:38 UTC
