### ISSUE TITLE
[Bug] logDNA does not use the env option

### ISSUE THREAD

**Issue by pydo** [logdna/python#25] opened 2019-01-29 19:32 UTC
### Description

I've been using the following logging config to work with logDNA (I stripped out the other handlers):

```
LOGGING_CONFIG = {
    'handlers': {
        'logDNA': {
            'level': 'DEBUG',
            'class': 'logging.handlers.LogDNAHandler',
            'key': os.environ['LOG_LOGDNA_KEY'],
            'options': {
                'app': f'auto_pitch_lib',
                'env': os.environ["ENVIRONMENT_NAME"],
                'index_meta': True
            }
        }
    },
    'root': {
        'level': 'DEBUG',
        'handlers': ['console', 'file', 'logDNA']
    }
}
```

## Problem

What I noticed is the `env` isn't set anywhere when searching through app logs in the LogDNA webapp.
The webapp doesn't seem to have any notion of environment, so my solution is to set the `ENVIRONMENT_NAME` in the app name.

```
LOGGING_CONFIG = {
    'handlers': {
        'logDNA': {
            'level': 'DEBUG',
            'class': 'logging.handlers.LogDNAHandler',
            'key': os.environ['LOG_LOGDNA_KEY'],
            'options': {
                'app': f'auto_pitch_lib-{os.environ["ENVIRONMENT_NAME"]}',
                'index_meta': True
            }
        }
    },
    'root': {
        'level': 'DEBUG',
        'handlers': ['console', 'file', 'logDNA']
    }
}
```

Is the `env` option legacy that needs to be removed? If so I think the readme should be updated. 
If the `env` is actually being used I'd like to know how to use it properly.

Thanks

**Comment by LYHuang** [comment] 2019-03-12 21:41
The `env` is setting at [here](https://github.com/logdna/python/blob/309eb1dde5d2957388f60fb9abf3ef820dd21c2f/logdna/logdna.py#L145) with `options` setting.
I can't reproduce the issue you have when I am testing it.
Can you provide more detail?

**Config**
```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'logdna': {
            'level': logging.DEBUG,
            'class': 'logging.handlers.LogDNAHandler',
            'key': 'key',
            'options': {
                'app': 'djapp',
                'env': 'djenv',
                'index_meta': True,
            },
        }
    },
    'loggers': {
        '': {
            'handlers': ['logdna'],
            'level': logging.DEBUG
        },
    },
}
```
**Result**
![image](https://user-images.githubusercontent.com/14082239/54238043-a136f600-44d4-11e9-8273-d56499059157.png)

**Comment by smusali** [comment] 2019-06-19 17:28
Closing this issue since it has already been answered

**Closed by smusali** 2019-06-19 17:28 UTC
Labels: question
