### ISSUE TITLE
interpolation not working in logging

### ISSUE THREAD

**Issue by henrythe9th** [logdna/python#24] opened 2019-01-13 05:31 UTC
Hi,

I'm following the tutorial and it looks like logging using the string interpolation `%s` doesn't seem to work with this library. Here's my simple code:

```python
import os
import logging
from logdna import LogDNAHandler


logger = logging.getLogger('logdna')
logger.setLevel(logging.INFO)

logdna_handler = LogDNAHandler('MY_API_KEY', {
  'hostname': 'myhostname',
  'max_length': False
})

logger.addHandler(logdna_handler)
logger.info('hello world from %s', 'test')
```

However, in the LogDNA UI, I only see the following: `hello world from %s`
![image](https://user-images.githubusercontent.com/644176/51081947-84479780-16ca-11e9-8090-21e5db27ac29.png)

Can you help advise?

Thanks,
Henry

**Comment by smusali** [comment] 2019-01-16 20:01
Hey @henrythe9th,

Yeah, we don't support this mainly because the second argument of the method is reserved for `options` having optional `level`, `app`, etc. information, as shown in examples [here](https://github.com/logdna/python#usage).

Instead, you can use [string formatting](https://www.programiz.com/python-programming/methods/string/format).

**Comment by henrythe9th** [comment] 2019-01-16 23:02
Thanks for the response. Hmm, the default python logger and lint best practice is to use lazy formatting as per the official python documentation:
https://docs.python.org/3/howto/logging.html#optimization

Also, I'm not sure if it's best practice to change the method signature of the built-in logger method?

Thanks for your help

**Comment by LYHuang** [comment] 2019-03-12 22:31
Hey,
I just did some test and I can't reproduce your issue,
can you provide more detail?
Here is the code I am using for testing.
```
import logging
from logdna.logdna import LogDNAHandler

def func1():
    return 'func1'
def func2():
    return 'func2'

log = logging.getLogger('logdna')
log.setLevel(logging.WARNING)
options = dict(hostname='pyhost', app='pyapp', env='pyenv')
options['index_meta'] = True
logdna_handler = LogDNAHandler(key, options)
log.addHandler(logdna_handler)

if log.isEnabledFor(logging.INFO):
    log.info('LogDNA test for python, %s, %s', func1(), func2())
if log.isEnabledFor(logging.ERROR):
    log.error('LogDNA test for python, %s, %s', func1(), func2())
```
![image](https://user-images.githubusercontent.com/14082239/54240534-8ddb5900-44db-11e9-81ba-b394a0873eb0.png)

**Comment by smusali** [comment] 2019-06-19 19:07
@henrythe9th, as @LYHuang said, we can't replicate the issue after testing. Can you provide us more details? Closing this issue for now.

**Closed by smusali** 2019-06-19 19:07 UTC
Labels: question
