### ISSUE TITLE
LogDNAHandler.emit fails with non-keyword arguments

### ISSUE THREAD

**Issue by drdaeman** [logdna/python#13] opened 2017-12-18 14:26 UTC
Hi. I've tried to add LogDNAHandler to logging configuration of some existing project and noticed that it started raise a lot of exceptions. If the record was logged with non-keyword arguments, like

    logger.debug("User %s is now %s", username, status)

Then logger would fail with `TypeError: tuple indices must be integers or slices, not str`. Still, that's a valid and reasonably common way to use standard library logging.

This happens because:

    opts = {}
    if 'args' in record:
        opts = record['args']
    ...
    if 'level' in opts:
        message['level'] = opts['level']

And `record["args"]` is a list, e.g.:

    {
        "args": ["drdaeman", "active"],
        "message: "User drdaeman is now active",
        "msg": "User %s is now %s",
        "levelname": "DEBUG",
        "levelno": 10,
        ....
    }

I know, the structured logging and keyword arguments are the way to go, but legacy logging code and quick hacks (to print some debug data quick) are reality.

Also, I'm not sure it is a good idea to use `record.args` at all - in standard library's `LogRecord`, its sole purpose is to convert from `msg` to `message`. Maybe this logic should be put behind some `options["use_args"]` flag.

**Comment by davzucky** [comment] 2017-12-27 15:27
With logDNA 1.2.3 I got the error
```
 ValueError: Unable to configure handler 'logDNA': __init__() got an unexpected keyword argument 'token'
```
When I revert to the version 1.2.2 everything is working again. I expect they are something the change on the way the keyword are handle

**Comment by respectus** [comment] 2018-01-04 20:42
Hi @drdaeman, thanks for reporting this issue. I wholeheartedly agree with you that your example is a valid and reasonable way to use a standard logging library. I am able to send the above debug statement properly formatted using the LogDNAHandler. Could you try my configuration? I believe there may be an issue with setting the default level to a low enough priority (DEBUG). Please do let me know if the following code does not work for you and we can further diagnose what the problem may be.

```
import logging
from logdna import LogDNAHandler

key = '<YOUR API KEY HERE>'
log = logging.getLogger('logdna')
# Should set level to lowest priority to send debug statements
log.setLevel(logging.DEBUG)
test = LogDNAHandler(key, { 'hostname': 'pytest1', 'index_meta': True })

log.addHandler(test)
username = "Me"
status = "working"
log.debug("User %s is now %s", username, status)
```

**Comment by respectus** [comment] 2018-02-06 21:45
Hi @drdaeman, 

     I hope you got a chance to try out my suggestion above. I'm closing this issue now, since I am not able to reproduce it. I would be glad to reopen it if you continue experiencing issues and we can debug further. Thanks for keeping up with this module!

**Closed by respectus** 2018-02-06 21:45 UTC
